### PR TITLE
Change license to be a free software license

### PR DESCRIPTION
**Pull request by Dev380**
Creative commons itself doesn't recommend using it's licenses for software: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
Additionally, the cc noncommercial licenses are not free as in freedom https://www.gnu.org/licenses/license-list#CC-BY-NC and it is not open source (see https://opensource.org/licenses/alphabetical and search for "noncommercial") The license is also not free culture https://creativecommons.org/share-your-work/public-domain/freeworks/ which are the types of licenses that CC recommends using.
I propose to change the project to a free software license https://www.gnu.org/licenses/license-list since cc licenses weren't meant for software and the specific license isn't even free or open source,
I chose the GNU GPL just as an example, any free software license would work.

### CODE REVIEW

**Comment by Dev380** [comment]
I added a README notice because it was required and I forgot it.
CC Noncommercial licenses are also not compatible with any free or open source licenses, therefore every contributor must agree to the relicensing. So just ask everyone here https://github.com/Ladysnake/Illuminations/graphs/contributors

**Review by doctor4t — CHANGES_REQUESTED** [review]
Ladysnake is written without a "S" capitalization, so it would require changing it in the Readme.md.

GPL can't be run with proprietary software, except **Minecraft is proprietary software**. Therefore, you'd need to add a specific clause for Minecraft to the license. I suggest looking at what Requiem or Snow Mercy does.

**Comment by Dev380** [comment]
Oops, sorry. Will change capitalization!
About the GPL thing, sorry about that. The mod's folder may or may not be considered linking, but you're right the risk is probably not worth taking. Does the LGPL v3 work for you? Since GNU made it clear that dynamic linking with Java is not a violation of the LGPL and Sodium is released under it and it hasn't caused them any trouble, and this license is a bit more compatible than the custom GPL.

**Comment by Dev380** [comment]
I'm going to keep the GPL license file because GNU recommends including both files when licensing under the LGPL since LGPL is just an extension of GPL.

**Comment by doctor4t** [comment]
I'd prefer to stick with GPL.

**Comment by Dev380** [comment]
Do you insist on using GPL v2 or did you just not bother switching to v3?
So should I do GPL v2 only, GPL v2 or later, or GPL v3 or later?

**Comment by doctor4t** [comment]
GPLv3 or later sounds good to me.

**Comment by Dev380** [comment]
Alright, done!
Changes in this PR so far:
Changed license to GPL v3 or later, with an MC linking exception
Changed README to add a copyright and warranty notice.

**Comment by doctor4t** [comment]
Looks good to me.

**Review by Pyrofab — APPROVED** [review]
Technically to comply with GNU's suggestion you should add a license header to all code files, but this should already be enough.

**Review by doctor4t — APPROVED** [review]

**Pull request merged**
