### PR TITLE
Create fr_fr.json

### PR DESCRIPTION
**Pull request by Lykrast**
I don't know if I was more surprised there was only 1 entry to translate, or that there was one at all. Anyway, enjoy a translation.

### CODE REVIEW

**Comment by Pyrofab** [comment]
That's one very timely PR. But I don't know if the line you translated is or will be used at all...

**Comment by Lykrast** [comment]
Well that would be unfortunate...

**Comment by doctor4t** [comment]
Thanks for the PR. The reason Illuminations has one lang entry is because Illuminations is mainly client only and there's no need for text when the only thing the mod does is display pretty particles; but with the latest update, I added the bugball item (that needs the server to also have Illuminations in order to be used).

**Comment by doctor4t** [comment]
Also, happy Hacktoberfest 🎃

**Pull request merged**
