### PR TITLE
More pride flags

### PR DESCRIPTION
**Pull request by Joththeboop**
we got a
number one victory royale
yeah fortnite we bout to get down 
(get down)
10 kills on the board right now
just wiped out Tomato Town
my friend just got downed
i revived him
now were heading south-bound
now were in the Pleasant Park streets
look at the map
go to the marked sheet

take me to your xbox to play fortnite today
you can take me to moisty mire
but not loot lake
i really love to
chug jug with you
we can be pro fortnite gamers

### CODE REVIEW

**Comment by doctor4t** [comment]
image

**Comment by Pyrofab** [comment]
This PR is super gay

I approve 💯💯

**Review by doctor4t — CHANGES_REQUESTED** [review]
- Variables should be registered, they can't be assigned just like that. Look towards the start of the file.
- Variable names shouldn't just be "Bi", "Ace", etc... They are all supposed to have the suffix "_pride"

**Comment by Joththeboop** [comment]
fixed the file names and registered the vars

**Review by doctor4t — APPROVED** [review]

**Pull request merged**
